language: node_js
node_js:
  - '0.12'
  - '4'
  - '6'
  - '7'
deploy:
  provider: npm
  email: nwoltman@outlook.com
  api_key:
    secure: gqFTLXqC+uTXjQO+vFTdxALHMidw5RqJ53EybHQpsFWpnJFhCdCS8urkR6oWn6TFycaAjWH763M4cffAu0SjPQ2xk+yprQfno58CxCos+Q/YiBqoHnX5p79FC8UDUFxWwxnlyA2iBX/7rHma4XCGirHyAFvcCPO6ln0xPCzRifrl/FqpLqSAtlz86pIa69WNSuTXc7jBpoEanm4/cZGMESt8cBs72Y/2rDJ4aArnrsHl4JBVdVsRGNl4fGQJiAG1Q7UR+Wz6Ko29iu5cm0L+XLyLBYDOvpWFjSezvwTgmqG1h5CgkZxDUsQG/h6NBavw5Id8vQ1KFHEz1XitLLSmJNoF/h2UpiJ82nuUlSF+its5pBNcSBkN/nVoqocBcLck9s8eQarjiAbIbas4lcgI1C6BqiXehAERY9fyp6pJc3/ymPiYczWpcWJZmKVrteDu6ZGzCQSE4nqeQ2Hjuw/3onv+WrPZ08s1v8yh1hQDaAvZqWiA5TbSXLl5vSDhLeQ3hG7gjDuhcZTnNh4xVrx8UJBGuujUbmC1vFM6dkzYvCEn3CaomX3+JFCVeGUPGXBRGME7SJpHCL2DiP2eqn+UtTS+zQczXqti0vX8XUzYvXpBSSkfFoDvfqVTCZsHxgQYSY5hTJEF9T2K5+obp4zObchs679icotYvs1bKPGm4mM=
  on:
    tags: true
