language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'
  - '6'
deploy:
  provider: npm
  email: nwoltman@outlook.com
  api_key:
    secure: pSBWLFpvslrfC4takP91VA6KrcuPyP3H47/I4IxVlYyj/9LREFtkx/ucvy7XCwh17TMcxgwYWMMwx9aP2DwFqs4ZlgiObSL99wW3PxAI23HigUJjUsQiwc7Zve/i7wCiPN8EozkSpS4DcfBHrTl61io9nla4ySs+dc3s9xrJDg2GgKw1U3C/5jAZLlnZRixZ0iuET6L6uljB4Ng59o0CCKKqE24XhAGoFd0xsyoJbqE6yUAbDG2fBuECfJViowEi3fWrR9aZ6SMbkHNacZYzBisbdFCAB5ELHMpWAE18FavMpV3MLDaI8Ay4KbR0Jx9msQE+BIIvDC/nQEYPd/YkhMlbP2EEAfW6lIEieVF7fsKpMPdwKe3mboQa+ZTGCHcXF5P2vDZfcgNY2B84SHziuOmS3ZTNaj7JF0/YVWhyIwxBuaUWhqlPZ4IzHGq84KbwXMDZN1Yb1SFP/2k28chA9G6TFkvxK7/vfYsDAsmlfDMIxw30tx7rmkfxzg5n6700CXZF4cL1Paeq3pC27yBwC6yeQumerYpqwnBHhadaSfiJAx0YEhF9ShBjw2v46xGpwSW8TEDfbv5MUp8Jw0F+pYmcoO552DPDVcTVKBUGvIr0dPYhC2M9GbDZ1bFvm4B6zfBvPupazJADMfmNoHcAge65UbVDeqFOGGX3OPs98Yw=
  on:
    tags: true
